#define PEACH_CONFIG_READER_PARSER_EQUAL                           1
#define PEACH_CONFIG_READER_PARSER_DOT                             2
#define PEACH_CONFIG_READER_PARSER_COLON                           3
#define PEACH_CONFIG_READER_PARSER_BRACKETL                        4
#define PEACH_CONFIG_READER_PARSER_SQUAREBRACKETL                  5
#define PEACH_CONFIG_READER_PARSER_PATH                            6
#define PEACH_CONFIG_READER_PARSER_TEXT                            7
#define PEACH_CONFIG_READER_PARSER_SEMICOLON                       8
#define PEACH_CONFIG_READER_PARSER_BRACKETR                        9
#define PEACH_CONFIG_READER_PARSER_SQUAREBRACKETR                 10
